# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'freeseer_configtool_ui.ui'
#
# Created: Fri Feb 11 23:21:35 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_configure(object):
    def setupUi(self, configure):
        configure.setObjectName("configure")
        configure.resize(568, 505)
        self.configureTab = QtGui.QTabWidget(configure)
        self.configureTab.setEnabled(True)
        self.configureTab.setGeometry(QtCore.QRect(0, 0, 567, 441))
        self.configureTab.setCursor(QtCore.Qt.ArrowCursor)
        self.configureTab.setTabPosition(QtGui.QTabWidget.North)
        self.configureTab.setElideMode(QtCore.Qt.ElideNone)
        self.configureTab.setUsesScrollButtons(True)
        self.configureTab.setDocumentMode(False)
        self.configureTab.setTabsClosable(False)
        self.configureTab.setObjectName("configureTab")
        self.SourceSetting = QtGui.QWidget()
        self.SourceSetting.setObjectName("SourceSetting")
        self.VideoSourceBox = QtGui.QGroupBox(self.SourceSetting)
        self.VideoSourceBox.setGeometry(QtCore.QRect(14, 10, 531, 181))
        self.VideoSourceBox.setFlat(False)
        self.VideoSourceBox.setCheckable(False)
        self.VideoSourceBox.setObjectName("VideoSourceBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.VideoSourceBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtGui.QWidget(self.VideoSourceBox)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.localDesktopButton_2 = QtGui.QRadioButton(self.widget_2)
        self.localDesktopButton_2.setEnabled(False)
        self.localDesktopButton_2.setChecked(True)
        self.localDesktopButton_2.setObjectName("localDesktopButton_2")
        self.verticalLayout_11.addWidget(self.localDesktopButton_2)
        self.hardwareButton_2 = QtGui.QRadioButton(self.widget_2)
        self.hardwareButton_2.setEnabled(False)
        self.hardwareButton_2.setObjectName("hardwareButton_2")
        self.verticalLayout_11.addWidget(self.hardwareButton_2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.localDesktopBox_2 = QtGui.QGroupBox(self.VideoSourceBox)
        self.localDesktopBox_2.setMinimumSize(QtCore.QSize(0, 138))
        self.localDesktopBox_2.setObjectName("localDesktopBox_2")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.localDesktopBox_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.recordLocalDesktopButton_2 = QtGui.QRadioButton(self.localDesktopBox_2)
        self.recordLocalDesktopButton_2.setChecked(True)
        self.recordLocalDesktopButton_2.setObjectName("recordLocalDesktopButton_2")
        self.verticalLayout_12.addWidget(self.recordLocalDesktopButton_2)
        self.recordLocalAreaButton_2 = QtGui.QRadioButton(self.localDesktopBox_2)
        self.recordLocalAreaButton_2.setEnabled(True)
        self.recordLocalAreaButton_2.setObjectName("recordLocalAreaButton_2")
        self.verticalLayout_12.addWidget(self.recordLocalAreaButton_2)
        self.recordLocalWindowButton_2 = QtGui.QRadioButton(self.localDesktopBox_2)
        self.recordLocalWindowButton_2.setEnabled(False)
        self.recordLocalWindowButton_2.setObjectName("recordLocalWindowButton_2")
        self.verticalLayout_12.addWidget(self.recordLocalWindowButton_2)
        self.areaButton_2 = QtGui.QPushButton(self.localDesktopBox_2)
        self.areaButton_2.setEnabled(False)
        self.areaButton_2.setObjectName("areaButton_2")
        self.verticalLayout_12.addWidget(self.areaButton_2)
        self.horizontalLayout_2.addWidget(self.localDesktopBox_2)
        self.hardwareBox_2 = QtGui.QGroupBox(self.VideoSourceBox)
        self.hardwareBox_2.setMinimumSize(QtCore.QSize(0, 138))
        self.hardwareBox_2.setFlat(False)
        self.hardwareBox_2.setCheckable(False)
        self.hardwareBox_2.setChecked(False)
        self.hardwareBox_2.setObjectName("hardwareBox_2")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.hardwareBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.usbsrcButton_2 = QtGui.QRadioButton(self.hardwareBox_2)
        self.usbsrcButton_2.setEnabled(False)
        self.usbsrcButton_2.setChecked(True)
        self.usbsrcButton_2.setObjectName("usbsrcButton_2")
        self.verticalLayout_13.addWidget(self.usbsrcButton_2)
        self.firewiresrcButton_2 = QtGui.QRadioButton(self.hardwareBox_2)
        self.firewiresrcButton_2.setEnabled(False)
        self.firewiresrcButton_2.setObjectName("firewiresrcButton_2")
        self.verticalLayout_13.addWidget(self.firewiresrcButton_2)
        self.videoDeviceList_2 = QtGui.QComboBox(self.hardwareBox_2)
        self.videoDeviceList_2.setObjectName("videoDeviceList_2")
        self.verticalLayout_13.addWidget(self.videoDeviceList_2)
        self.horizontalLayout_2.addWidget(self.hardwareBox_2)
        self.SoundSourcegroupBox = QtGui.QGroupBox(self.SourceSetting)
        self.SoundSourcegroupBox.setGeometry(QtCore.QRect(10, 200, 521, 161))
        self.SoundSourcegroupBox.setObjectName("SoundSourcegroupBox")
        self.horizontalLayoutWidget = QtGui.QWidget(self.SoundSourcegroupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 501, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.audioSourceList = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.audioSourceList.setObjectName("audioSourceList")
        self.horizontalLayout.addWidget(self.audioSourceList)
        self.configureTab.addTab(self.SourceSetting, "")
        self.Videosetting = QtGui.QWidget()
        self.Videosetting.setObjectName("Videosetting")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Videosetting)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VideoQualitygroupBox = QtGui.QGroupBox(self.Videosetting)
        self.VideoQualitygroupBox.setObjectName("VideoQualitygroupBox")
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.VideoQualitygroupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 521, 81))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_VideoQuality_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_VideoQuality_2.setObjectName("horizontalLayout_VideoQuality_2")
        self.label_Video_Quality_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_Video_Quality_2.setObjectName("label_Video_Quality_2")
        self.horizontalLayout_VideoQuality_2.addWidget(self.label_Video_Quality_2)
        self.resolutionComboBox_2 = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.resolutionComboBox_2.setObjectName("resolutionComboBox_2")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.resolutionComboBox_2.addItem("")
        self.horizontalLayout_VideoQuality_2.addWidget(self.resolutionComboBox_2)
        self.EnableStreaminggroupBox = QtGui.QGroupBox(self.VideoQualitygroupBox)
        self.EnableStreaminggroupBox.setGeometry(QtCore.QRect(10, 120, 521, 261))
        self.EnableStreaminggroupBox.setCheckable(True)
        self.EnableStreaminggroupBox.setChecked(False)
        self.EnableStreaminggroupBox.setObjectName("EnableStreaminggroupBox")
        self.layoutWidget_7 = QtGui.QWidget(self.EnableStreaminggroupBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 501, 231))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_EnableStreaming_2 = QtGui.QGridLayout(self.layoutWidget_7)
        self.gridLayout_EnableStreaming_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_EnableStreaming_2.setObjectName("gridLayout_EnableStreaming_2")
        self.LineEditURL_2 = QtGui.QLineEdit(self.layoutWidget_7)
        self.LineEditURL_2.setText("")
        self.LineEditURL_2.setObjectName("LineEditURL_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.LineEditURL_2, 0, 1, 1, 1)
        self.LineEdit_Password_2 = QtGui.QLineEdit(self.layoutWidget_7)
        self.LineEdit_Password_2.setEchoMode(QtGui.QLineEdit.Password)
        self.LineEdit_Password_2.setObjectName("LineEdit_Password_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.LineEdit_Password_2, 3, 1, 1, 1)
        self.Label_MountPoint_2 = QtGui.QLabel(self.layoutWidget_7)
        self.Label_MountPoint_2.setObjectName("Label_MountPoint_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.Label_MountPoint_2, 2, 0, 1, 1)
        self.lineEditMountPoint_2 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEditMountPoint_2.setObjectName("lineEditMountPoint_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.lineEditMountPoint_2, 2, 1, 1, 1)
        self.label_Port_2 = QtGui.QLabel(self.layoutWidget_7)
        self.label_Port_2.setObjectName("label_Port_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.label_Port_2, 1, 0, 1, 1)
        self.lineEditPort_2 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEditPort_2.setObjectName("lineEditPort_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.lineEditPort_2, 1, 1, 1, 1)
        self.label_URL_IP_2 = QtGui.QLabel(self.layoutWidget_7)
        self.label_URL_IP_2.setObjectName("label_URL_IP_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.label_URL_IP_2, 0, 0, 1, 1)
        self.label_Password_2 = QtGui.QLabel(self.layoutWidget_7)
        self.label_Password_2.setObjectName("label_Password_2")
        self.gridLayout_EnableStreaming_2.addWidget(self.label_Password_2, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.VideoQualitygroupBox)
        self.configureTab.addTab(self.Videosetting, "")
        self.Extrasetting = QtGui.QWidget()
        self.Extrasetting.setObjectName("Extrasetting")
        self.AutoHidegroupBox = QtGui.QGroupBox(self.Extrasetting)
        self.AutoHidegroupBox.setGeometry(QtCore.QRect(20, 20, 511, 80))
        self.AutoHidegroupBox.setObjectName("AutoHidegroupBox")
        self.autoHideCheckbox = QtGui.QCheckBox(self.AutoHidegroupBox)
        self.autoHideCheckbox.setGeometry(QtCore.QRect(30, 10, 451, 64))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoHideCheckbox.sizePolicy().hasHeightForWidth())
        self.autoHideCheckbox.setSizePolicy(sizePolicy)
        self.autoHideCheckbox.setMinimumSize(QtCore.QSize(0, 0))
        self.autoHideCheckbox.setMaximumSize(QtCore.QSize(16777215, 64))
        self.autoHideCheckbox.setChecked(True)
        self.autoHideCheckbox.setObjectName("autoHideCheckbox")
        self.ShortKeysgroupBox = QtGui.QGroupBox(self.Extrasetting)
        self.ShortKeysgroupBox.setGeometry(QtCore.QRect(20, 100, 511, 131))
        self.ShortKeysgroupBox.setObjectName("ShortKeysgroupBox")
        self.layoutWidget_4 = QtGui.QWidget(self.ShortKeysgroupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 501, 101))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_Shorkeys = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_Shorkeys.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_Shorkeys.setObjectName("gridLayout_Shorkeys")
        self.shortRecordLabel_4 = QtGui.QLabel(self.layoutWidget_4)
        self.shortRecordLabel_4.setIndent(15)
        self.shortRecordLabel_4.setObjectName("shortRecordLabel_4")
        self.gridLayout_Shorkeys.addWidget(self.shortRecordLabel_4, 0, 0, 1, 1)
        self.shortStopLabel_4 = QtGui.QLabel(self.layoutWidget_4)
        self.shortStopLabel_4.setIndent(15)
        self.shortStopLabel_4.setObjectName("shortStopLabel_4")
        self.gridLayout_Shorkeys.addWidget(self.shortStopLabel_4, 1, 0, 1, 1)
        self.shortRecordLineEdit_4 = QtGui.QLineEdit(self.layoutWidget_4)
        self.shortRecordLineEdit_4.setObjectName("shortRecordLineEdit_4")
        self.gridLayout_Shorkeys.addWidget(self.shortRecordLineEdit_4, 0, 1, 1, 1)
        self.shortStopLineEdit_4 = QtGui.QLineEdit(self.layoutWidget_4)
        self.shortStopLineEdit_4.setObjectName("shortStopLineEdit_4")
        self.gridLayout_Shorkeys.addWidget(self.shortStopLineEdit_4, 1, 1, 1, 1)
        self.LocationgroupBox = QtGui.QGroupBox(self.Extrasetting)
        self.LocationgroupBox.setGeometry(QtCore.QRect(20, 250, 511, 141))
        self.LocationgroupBox.setObjectName("LocationgroupBox")
        self.layoutWidget_5 = QtGui.QWidget(self.LocationgroupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 30, 501, 101))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_Location = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_Location.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_Location.setObjectName("gridLayout_Location")
        self.videoDirectoryButton = QtGui.QToolButton(self.layoutWidget_5)
        self.videoDirectoryButton.setObjectName("videoDirectoryButton")
        self.gridLayout_Location.addWidget(self.videoDirectoryButton, 0, 2, 1, 1)
        self.videoDirectoryLabel = QtGui.QLabel(self.layoutWidget_5)
        self.videoDirectoryLabel.setIndent(15)
        self.videoDirectoryLabel.setObjectName("videoDirectoryLabel")
        self.gridLayout_Location.addWidget(self.videoDirectoryLabel, 0, 0, 1, 1)
        self.videoDirectoryLineEdit = QtGui.QLineEdit(self.layoutWidget_5)
        self.videoDirectoryLineEdit.setObjectName("videoDirectoryLineEdit")
        self.gridLayout_Location.addWidget(self.videoDirectoryLineEdit, 0, 1, 1, 1)
        self.configureTab.addTab(self.Extrasetting, "")
        self.layoutWidget = QtGui.QWidget(configure)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 450, 321, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.applySettingsButton = QtGui.QPushButton(self.layoutWidget)
        self.applySettingsButton.setMouseTracking(False)
        self.applySettingsButton.setDefault(False)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.horizontalLayout_7.addWidget(self.applySettingsButton)
        self.resetSettingsButton = QtGui.QPushButton(self.layoutWidget)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.horizontalLayout_7.addWidget(self.resetSettingsButton)
        self.label_5.setBuddy(self.audioSourceList)
        self.label_Video_Quality_2.setBuddy(configure.resolutionComboBox)
        self.Label_MountPoint_2.setBuddy(configure.lineEditMountPoint)
        self.label_Port_2.setBuddy(configure.lineEditPort)
        self.label_URL_IP_2.setBuddy(configure.LineEditURL)
        self.label_Password_2.setBuddy(configure.LineEdit_Password)
        self.shortRecordLabel_4.setBuddy(self.shortRecordLineEdit_4)
        self.shortStopLabel_4.setBuddy(self.shortStopLineEdit_4)
        self.videoDirectoryLabel.setBuddy(self.videoDirectoryLineEdit)

        self.retranslateUi(configure)
        self.configureTab.setCurrentIndex(2)
        QtCore.QObject.connect(self.localDesktopButton_2, QtCore.SIGNAL("toggled(bool)"), self.localDesktopBox_2.setVisible)
        QtCore.QObject.connect(self.recordLocalAreaButton_2, QtCore.SIGNAL("toggled(bool)"), self.areaButton_2.setVisible)
        QtCore.QObject.connect(self.hardwareButton_2, QtCore.SIGNAL("toggled(bool)"), self.hardwareBox_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(configure)
        configure.setTabOrder(self.applySettingsButton, self.resetSettingsButton)
        configure.setTabOrder(self.resetSettingsButton, self.configureTab)
        configure.setTabOrder(self.configureTab, self.localDesktopButton_2)
        configure.setTabOrder(self.localDesktopButton_2, self.hardwareButton_2)
        configure.setTabOrder(self.hardwareButton_2, self.recordLocalDesktopButton_2)
        configure.setTabOrder(self.recordLocalDesktopButton_2, self.recordLocalAreaButton_2)
        configure.setTabOrder(self.recordLocalAreaButton_2, self.recordLocalWindowButton_2)
        configure.setTabOrder(self.recordLocalWindowButton_2, self.areaButton_2)
        configure.setTabOrder(self.areaButton_2, self.usbsrcButton_2)
        configure.setTabOrder(self.usbsrcButton_2, self.firewiresrcButton_2)
        configure.setTabOrder(self.firewiresrcButton_2, self.videoDeviceList_2)
        configure.setTabOrder(self.videoDeviceList_2, self.audioSourceList)
        configure.setTabOrder(self.audioSourceList, self.resolutionComboBox_2)
        configure.setTabOrder(self.resolutionComboBox_2, self.EnableStreaminggroupBox)
        configure.setTabOrder(self.EnableStreaminggroupBox, self.LineEditURL_2)
        configure.setTabOrder(self.LineEditURL_2, self.lineEditPort_2)
        configure.setTabOrder(self.lineEditPort_2, self.lineEditMountPoint_2)
        configure.setTabOrder(self.lineEditMountPoint_2, self.LineEdit_Password_2)
        configure.setTabOrder(self.LineEdit_Password_2, self.autoHideCheckbox)
        configure.setTabOrder(self.autoHideCheckbox, self.shortRecordLineEdit_4)
        configure.setTabOrder(self.shortRecordLineEdit_4, self.shortStopLineEdit_4)
        configure.setTabOrder(self.shortStopLineEdit_4, self.videoDirectoryLineEdit)
        configure.setTabOrder(self.videoDirectoryLineEdit, self.videoDirectoryButton)
        configure.setTabOrder(self.videoDirectoryButton, configure.LineEdit_Password)
        configure.setTabOrder(configure.LineEdit_Password, configure.resolutionComboBox)
        configure.setTabOrder(configure.resolutionComboBox, configure.lineEditPort)
        configure.setTabOrder(configure.lineEditPort, configure.LineEditURL)
        configure.setTabOrder(configure.LineEditURL, configure.lineEditMountPoint)
        configure.setTabOrder(configure.lineEditMountPoint, configure.VideoStreamingBox)

    def retranslateUi(self, configure):
        configure.setWindowTitle(QtGui.QApplication.translate("configure", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.VideoSourceBox.setTitle(QtGui.QApplication.translate("configure", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.localDesktopButton_2.setToolTip(QtGui.QApplication.translate("configure", "Select this option to record the local desktop. \n"
"Freeseer currently only supports recording the full desktop. \n"
"We plan to support window and area modes in future versions.", None, QtGui.QApplication.UnicodeUTF8))
        self.localDesktopButton_2.setText(QtGui.QApplication.translate("configure", "&Local Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.hardwareButton_2.setToolTip(QtGui.QApplication.translate("configure", "Select hardware to record from either a usb device or firewire device.\n"
"\n"
"Freeseer finds USB devices by scanning /dev/videoX starting from index 0.\n"
"\n"
"Freeseer finds Firewire devices by scanning /dev/fwX starting from index 1.", None, QtGui.QApplication.UnicodeUTF8))
        self.hardwareButton_2.setText(QtGui.QApplication.translate("configure", "&Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.localDesktopBox_2.setTitle(QtGui.QApplication.translate("configure", "Local Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalDesktopButton_2.setToolTip(QtGui.QApplication.translate("configure", "Select this option to record the entire desktop.", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalDesktopButton_2.setText(QtGui.QApplication.translate("configure", "&Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalAreaButton_2.setToolTip(QtGui.QApplication.translate("configure", "Select this option to record an small area of the desktop.", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalAreaButton_2.setText(QtGui.QApplication.translate("configure", "&Area", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalWindowButton_2.setToolTip(QtGui.QApplication.translate("configure", "This feature is currently not yet implemented.", None, QtGui.QApplication.UnicodeUTF8))
        self.recordLocalWindowButton_2.setText(QtGui.QApplication.translate("configure", "&Window (Not Supported)", None, QtGui.QApplication.UnicodeUTF8))
        self.areaButton_2.setText(QtGui.QApplication.translate("configure", "Set Area", None, QtGui.QApplication.UnicodeUTF8))
        self.hardwareBox_2.setTitle(QtGui.QApplication.translate("configure", "Hardware", None, QtGui.QApplication.UnicodeUTF8))
        self.usbsrcButton_2.setToolTip(QtGui.QApplication.translate("configure", "Use this option to record from a usb device.\n"
"\n"
"This option tries the v4l2src driver\n"
"and falls back to the v4lsrc driver if\n"
"v4l2src does not work.", None, QtGui.QApplication.UnicodeUTF8))
        self.usbsrcButton_2.setText(QtGui.QApplication.translate("configure", "&usb device", None, QtGui.QApplication.UnicodeUTF8))
        self.firewiresrcButton_2.setToolTip(QtGui.QApplication.translate("configure", "Firewire mode uses dv1394src as the video driver.", None, QtGui.QApplication.UnicodeUTF8))
        self.firewiresrcButton_2.setText(QtGui.QApplication.translate("configure", "&firewire device", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDeviceList_2.setToolTip(QtGui.QApplication.translate("configure", "Select the video device to record from.", None, QtGui.QApplication.UnicodeUTF8))
        self.SoundSourcegroupBox.setTitle(QtGui.QApplication.translate("configure", "Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("configure", "&Sound Source", None, QtGui.QApplication.UnicodeUTF8))
        self.audioSourceList.setToolTip(QtGui.QApplication.translate("configure", "Select the audio source to use for recording.", None, QtGui.QApplication.UnicodeUTF8))
        self.configureTab.setTabText(self.configureTab.indexOf(self.SourceSetting), QtGui.QApplication.translate("configure", "Source Setting ", None, QtGui.QApplication.UnicodeUTF8))
        self.VideoQualitygroupBox.setTitle(QtGui.QApplication.translate("configure", "Video Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Video_Quality_2.setText(QtGui.QApplication.translate("configure", "&Video Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(0, QtGui.QApplication.translate("configure", "NONE", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(1, QtGui.QApplication.translate("configure", "360P(Low)", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(2, QtGui.QApplication.translate("configure", "480P(Medium)", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(3, QtGui.QApplication.translate("configure", "720P(High)", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(4, QtGui.QApplication.translate("configure", "1080P(Extreme)", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(5, QtGui.QApplication.translate("configure", "640x480", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(6, QtGui.QApplication.translate("configure", "800x600", None, QtGui.QApplication.UnicodeUTF8))
        self.resolutionComboBox_2.setItemText(7, QtGui.QApplication.translate("configure", "1024x768", None, QtGui.QApplication.UnicodeUTF8))
        self.EnableStreaminggroupBox.setTitle(QtGui.QApplication.translate("configure", "Enable Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.Label_MountPoint_2.setText(QtGui.QApplication.translate("configure", "&Mount point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Port_2.setText(QtGui.QApplication.translate("configure", "&Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_URL_IP_2.setText(QtGui.QApplication.translate("configure", "&URL/IP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Password_2.setText(QtGui.QApplication.translate("configure", "&Password", None, QtGui.QApplication.UnicodeUTF8))
        self.configureTab.setTabText(self.configureTab.indexOf(self.Videosetting), QtGui.QApplication.translate("configure", "Video setting", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoHidegroupBox.setTitle(QtGui.QApplication.translate("configure", "Auto Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.autoHideCheckbox.setToolTip(QtGui.QApplication.translate("configure", "Enables auto-hide to system tray.", None, QtGui.QApplication.UnicodeUTF8))
        self.autoHideCheckbox.setText(QtGui.QApplication.translate("configure", "&Enable Auto-Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.ShortKeysgroupBox.setTitle(QtGui.QApplication.translate("configure", "ShortKeys", None, QtGui.QApplication.UnicodeUTF8))
        self.shortRecordLabel_4.setText(QtGui.QApplication.translate("configure", "&Record", None, QtGui.QApplication.UnicodeUTF8))
        self.shortStopLabel_4.setText(QtGui.QApplication.translate("configure", "&Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.LocationgroupBox.setTitle(QtGui.QApplication.translate("configure", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDirectoryButton.setText(QtGui.QApplication.translate("configure", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDirectoryLabel.setText(QtGui.QApplication.translate("configure", "&Video Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.configureTab.setTabText(self.configureTab.indexOf(self.Extrasetting), QtGui.QApplication.translate("configure", "Extra setting", None, QtGui.QApplication.UnicodeUTF8))
        self.applySettingsButton.setText(QtGui.QApplication.translate("configure", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.resetSettingsButton.setText(QtGui.QApplication.translate("configure", "&Reset", None, QtGui.QApplication.UnicodeUTF8))

